### PR TITLE
Add info on merging

### PR DESCRIPTION
**Pull request by bgantick**

### CODE REVIEW

**Comment by abea** [comment]
This seems to imply this rule is for all PRs. You don't mean for two approvals for client project PRs, right?

**Comment by bgantick** [comment]
Nope - modules/public repos too

**Comment by boutell** [comment]
Same Q. Also at some point two approvals will make sense for apostrophe PRs, but taking a meaningful look at the code with one person is often all there is time for.

**Comment by austinstarin** [comment]
I think we could clarify this rule for all internal tools, boilerplates, npm modules, etc.

**Pull request merged**
