### PR TITLE
Starts a preferred modules file

### PR DESCRIPTION
**Pull request by abea**
To start tracking our preferred third party modules for common needs.

### CODE REVIEW

**Comment by austinstarin** [comment]
@abea should we have a preferred/vetted libraries section in js/css sections etc.?

**Comment by abea** [comment]
I think it makes sense on its own since some cross boundaries (e.g., CLNDR). Once we have a bunch we could create sections within the file.

**Comment by austinstarin** [comment]
OK, is modules the right word for this section? Is it doing to be specific to npm modules?

**Comment by abea** [comment]
Updated the file name and language.

**Pull request merged**
