### PR TITLE
Replacing anchors with headings

### PR DESCRIPTION
**Pull request by abea**
Replaces manually-written anchor links to resolve https://github.com/punkave/best-practices/issues/70.

### CODE REVIEW

**Comment by austinstarin** [comment]
Aren't we loosing the ability to link to specific items in the document?

**Comment by abea** [comment]
Nope, Github links all headings. This is one of the new H3s. https://github.com/punkave/best-practices/blob/hotfix/headings/accessibility.md#image-html-tags

**Comment by austinstarin** [comment]
Ah, great I see what you're doing now. 👌  If you feel passionately about making this update can you make it across all sections in on PR so it's consistent?

**Comment by abea** [comment]
I think they're all done. I added some formatting to the CI page since there wasn't any before. If this is something we're not interested that's fine as well.

**Comment by austinstarin** [comment]
Thanks!

**Pull request merged**
